import { z } from 'zod';
import data from '../data/stages.json';

export const eventSchema = z.object({id:z.string(),beat:z.number().nonnegative(),targetAngle:z.union([z.literal(15),z.literal(30),z.literal(45),z.literal(90),z.literal(120),z.literal('dogeza')]),question:z.string(),speakerId:z.string().default('reporter'),holdBeats:z.number().optional(),isFakeCue:z.boolean().optional(),timingWindowMs:z.number().optional(),angleTolerance:z.number().optional(),projectileOnMiss:z.string().optional(),cameraCue:z.enum(['push','shake','flash','closeup']).optional()});
export const stageSchema=z.object({id:z.string(),title:z.string(),bpm:z.number().min(40).max(200),chapter:z.number(),difficulty:z.number(),backgroundId:z.string(),offsetSeconds:z.number().default(0),timeSignature:z.tuple([z.number(),z.number()]).default([4,4]),musicId:z.string().default('panic-jazz'),events:z.array(eventSchema)});
export type Stage=z.infer<typeof stageSchema>;
export type ApologyEvent=z.infer<typeof eventSchema>;
export const stages:Stage[]=data.stages.map(s=>stageSchema.parse({...s,events:data.patterns[s.pattern as keyof typeof data.patterns].map((e,i)=>({...e,id:`${s.id}-${i}`,speakerId:`reporter-${i%3}`}))}));
export type Grade='PERFECT'|'GREAT'|'GOOD'|'MISS';
export function gradeTiming(ms:number):Grade {const a=Math.abs(ms);return a<=45?'PERFECT':a<=90?'GREAT':a<=140?'GOOD':'MISS';}
export function gradeAngle(deg:number):Grade {const a=Math.abs(deg);return a<=4?'PERFECT':a<=8?'GREAT':a<=12?'GOOD':'MISS';}
export function meanDeviation(samples:number[],target:number){return samples.length?samples.reduce((s,a)=>s+Math.abs(a-target),0)/samples.length:0;}
export function correctedError(inputSeconds:number,targetSeconds:number,latencyMs:number){return Math.round(((inputSeconds-targetSeconds)*1000-latencyMs)*1e6)/1e6;}
export function judge(ms:number,angleError:number,holdDeviation=0){const t=gradeTiming(ms),a=gradeAngle(angleError);const weights={PERFECT:1,GREAT:0.8,GOOD:0.5,MISS:0};const rawAccuracy=weights[t]*0.6+weights[a]*0.3+Math.max(0,1-holdDeviation/12)*0.1;const accuracy=Math.round(rawAccuracy*1e6)/1e6;const grade:Grade=t==='MISS'||a==='MISS'?'MISS':accuracy>=0.94?'PERFECT':accuracy>=0.75?'GREAT':'GOOD';return {grade,accuracy};}
export function seededRandom(seed:number){return ()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return ((t^t>>>14)>>>0)/4294967296;};}
export const projectiles=[['🥚','날계란','느긋한 포물선, 급하지 않은 재앙.','BallisticArc'],['🍅','잘 익은 토마토','오늘의 신선한 의견입니다.','StraightFast'],['🥧','생크림 파이','얼굴에 달콤한 침묵을.','Splash'],['🎈','물풍선','식은땀으로는 부족할 때.','Splash'],['☕','차가운 커피','정신이 번쩍 드는 콜드 브루.','BallisticArc'],['📃','구겨진 사과문','수정 요청이 도착했습니다.','Flutter'],['✈️','종이비행기','의견을 날려 보내드립니다.','Flutter'],['🗞️','돌돌 만 신문','오늘의 헤드라인을 직접 전달.','Bounce'],['🎤','마이크 커버','질문은 끝나지 않았습니다.','Bounce'],['🐔','고무 닭','삑! 재발 방지 대책은요?','ComicHoming'],['🩴','고무 슬리퍼','돌아오는 질문.','Boomerang'],['🥀','시든 꽃다발','진심 어린 위로인 것 같습니다.','Flutter'],['🥬','양배추','겹겹이 쌓인 책임.','Splash'],['❌','빨간 스티커','오답입니다. 다시 사과하세요.','StickyScreen'],['🧱','스펀지 벽돌','말랑말랑한 강경 대응.','Bounce'],['🍮','젤리 푸딩','흔들리는 신뢰를 형상화했습니다.','Splash'],['🫧','풍선껌','끈질긴 후속 질문.','StickyScreen'],['🍜','국수 그릇','머릿속이 복잡해지는 맛.','ComicHoming']];
