import {createActor,createMachine} from 'xstate';
import {audio} from './audio';
import {correctedError,judge,meanDeviation,seededRandom,type Stage,type Grade} from './core';
import {useProfile} from './store';
const machine=createMachine({id:'conference',initial:'idle',states:{idle:{on:{START:'playing'}},playing:{on:{PAUSE:'paused',END:'result',EXIT:'idle'}},paused:{on:{RESUME:'playing',EXIT:'idle',START:'playing'}},result:{on:{START:'playing',EXIT:'idle'}}}});
export type GameState={status:string;elapsed:number;beat:number;angle:number;dogeza:boolean;score:number;combo:number;maxCombo:number;trust:number;eventIndex:number;grade:string;error:number;accuracy:number;countdown:number;hit:number;hitId:number;judged:number;perfect:number;holding:boolean;};
export class GameEngine {
 actor=createActor(machine).start();state:GameState={status:'idle',elapsed:0,beat:0,angle:0,dogeza:false,score:0,combo:0,maxCombo:0,trust:100,eventIndex:0,grade:'READY',error:0,accuracy:0,countdown:3,hit:-1,hitId:0,judged:0,perfect:0,holding:false};stage:Stage|null=null;practice=false;origin=0;nextTick=0;pauseTime=0;timer:ReturnType<typeof setInterval>|null=null;listeners=new Set<()=>void>();random=seededRandom(1);hold:{index:number;ms:number;samples:number[];end:number}|null=null;lastSample=-1;lastDown=-10;downCount=0;dogezaStart=-1;gamepadPressed=false;
 subscribe=(fn:()=>void)=>{this.listeners.add(fn);return()=>{this.listeners.delete(fn);};};getSnapshot=()=>this.state;
 emit(patch:Partial<GameState>={}){this.state={...this.state,...patch};this.listeners.forEach(fn=>fn());}
 async start(stage:Stage,practice=false){this.stop();await audio.activate();audio.volume(useProfile.getState().options.volume);this.stage=stage;this.practice=practice;this.random=seededRandom(Number(stage.id)||42);this.actor.send({type:'START'});this.origin=audio.now+3*60/stage.bpm;this.nextTick=-6;this.hold=null;this.dogezaStart=-1;this.state={status:'playing',elapsed:0,beat:-3,angle:0,dogeza:false,score:0,combo:0,maxCombo:0,trust:100,eventIndex:0,grade:'READY',error:0,accuracy:0,countdown:3,hit:-1,hitId:0,judged:0,perfect:0,holding:false};this.emit();this.timer=setInterval(()=>this.update(),12);}
 update(){if(this.state.status!=='playing'||!this.stage)return;const {options}=useProfile.getState();audio.volume(options.volume);const spb=60/this.stage.bpm,elapsed=audio.now-this.origin,beat=elapsed/spb;while(this.origin+this.nextTick*spb/2<audio.now+.1){const t=this.origin+this.nextTick*spb/2;if(t>=audio.now){if(this.nextTick<0)audio.tone(t,850,.05,.15);else audio.beat(t,this.nextTick,options.audioBeat);}this.nextTick++;}
 this.emit({elapsed,beat,countdown:Math.max(0,Math.ceil(-beat))});if(elapsed<0)return;
 const gp=navigator.getGamepads?.()[0];if(gp){if(Math.abs(gp.axes[1])>.1)this.setAngle(this.state.angle+gp.axes[1]*2);if(gp.buttons[13]?.pressed&&!this.gamepadPressed)this.down();if(gp.buttons[0]?.pressed&&!this.gamepadPressed)this.submit();this.gamepadPressed=gp.buttons[0]?.pressed||gp.buttons[13]?.pressed;}
 if(this.hold){const sample=Math.floor(elapsed/.01);if(sample!==this.lastSample){this.hold.samples.push(this.state.dogeza?125:this.state.angle);this.lastSample=sample;}if(elapsed>=this.hold.end){const h=this.hold,e=this.stage.events[h.index];this.hold=null;const dev=meanDeviation(h.samples,e.targetAngle==='dogeza'?125:e.targetAngle);this.finish(judge(h.ms,dev,dev).grade,h.ms,judge(h.ms,dev,dev).accuracy);}}
 const e=this.stage.events[this.state.eventIndex];if(e&&!this.hold&&elapsed>e.beat*spb+.14+options.latency/1000){if(e.isFakeCue)this.emit({eventIndex:this.state.eventIndex+1,grade:'침착한 대응'});else if(this.practice)this.emit({eventIndex:this.state.eventIndex+1});else this.finish('MISS',150,0);}
 if(this.state.eventIndex>=this.stage.events.length&&elapsed>(this.stage.events.at(-1)!.beat+2)*spb){if(this.practice){this.origin=audio.now;this.nextTick=0;this.emit({eventIndex:0});}else this.end();}
 }
 setAngle(value:number){const o=useProfile.getState().options;let angle=Math.max(0,Math.min(125,value));const e=this.stage?.events[this.state.eventIndex];if(o.snap&&typeof e?.targetAngle==='number'&&Math.abs(angle-e.targetAngle)<5){if(this.state.angle!==e.targetAngle)navigator.vibrate?.(8);angle=e.targetAngle;}this.emit({angle,dogeza:false});}
 down(){if(audio.now-this.lastDown<.5)this.downCount++;else this.downCount=1;this.lastDown=audio.now;if(this.downCount>=2){this.dogezaStart=audio.now;this.emit({dogeza:true,angle:125});this.downCount=0;}}
 submit(){if(this.state.status!=='playing'||!this.stage||this.state.countdown>0||this.hold)return;const e=this.stage.events[this.state.eventIndex];if(!e)return;const o=useProfile.getState().options;if(o.assist){this.emit({angle:e.targetAngle==='dogeza'?125:e.targetAngle,dogeza:e.targetAngle==='dogeza'});this.dogezaStart=audio.now-.6;}
 const ms=correctedError(audio.now-this.origin,e.beat*60/this.stage.bpm,o.latency);if(Math.abs(ms)>650){this.emit({grade:'마지막 박자를 기다리세요'});return;}
 if(e.isFakeCue){this.finish('MISS',ms,0,'성급한 사과');return;}const angleError=e.targetAngle==='dogeza'?(this.state.dogeza&&audio.now-this.dogezaStart>=.6?0:125):Math.abs(this.state.angle-e.targetAngle);const result=judge(ms,angleError);if(e.holdBeats&&result.grade!=='MISS'){this.hold={index:this.state.eventIndex,ms,samples:[this.state.angle],end:(e.beat+e.holdBeats)*60/this.stage.bpm};this.emit({holding:true,grade:'HOLD · 자세 유지!'});return;}this.finish(result.grade,ms,result.accuracy);}
 finish(grade:Grade,error:number,accuracy:number,label?:string){const miss=grade==='MISS',combo=miss?0:this.state.combo+1,score=this.state.score+(miss?0:Math.round(accuracy*1000)*(1+Math.floor(combo/10)));const trust=Math.max(0,Math.min(100,this.state.trust+(miss?-14:3)));let hit=this.state.hit;if(miss){hit=Math.floor(this.random()*18);useProfile.getState().collect(hit);audio.tone(audio.now,130,.15,.2,'sawtooth');}else audio.tone(audio.now,grade==='PERFECT'?1046:784,.08,.1,'sine');this.emit({grade:label||grade,error,score,combo,maxCombo:Math.max(combo,this.state.maxCombo),trust,eventIndex:this.state.eventIndex+1,hit,hitId:this.state.hitId+(miss?1:0),judged:this.state.judged+1,perfect:this.state.perfect+(grade==='PERFECT'?1:0),accuracy:this.state.accuracy+accuracy,holding:false});if(trust===0&&!this.practice)this.end();}
 pause(){if(this.state.status!=='playing')return;this.pauseTime=audio.now;audio.stopSounds();this.actor.send({type:'PAUSE'});this.emit({status:'paused'});}
 async resume(){if(this.state.status!=='paused'||!this.stage)return;await audio.activate();const spb=60/this.stage.bpm;const frozen= this.pauseTime-this.origin;this.origin+=audio.now-this.pauseTime+3*spb;this.nextTick=Math.ceil(frozen/(spb/2));this.actor.send({type:'RESUME'});this.emit({status:'playing',countdown:3});const target=audio.now+3*spb;for(let i=0;i<3;i++)audio.tone(audio.now+i*spb,850,.05,.15);if(this.timer)clearInterval(this.timer);this.timer=setInterval(()=>{if(this.state.status!=='playing')return;if(audio.now<target)this.emit({countdown:Math.ceil((target-audio.now)/spb)});else this.update();},12);}
 end(){audio.stopSounds();if(this.timer)clearInterval(this.timer);this.actor.send({type:'END'});this.emit({status:'result'});if(this.stage)useProfile.getState().saveResult(this.stage.id,this.state.score,this.state.maxCombo,this.state.trust>0);}
 stop(){if(this.timer)clearInterval(this.timer);this.timer=null;audio.stopSounds();this.actor.send({type:'EXIT'});this.emit({status:'idle'});}
}
export const engine=new GameEngine();
