import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
test('title navigation, keyboard focus and options persistence',async({page})=>{await page.goto('/');await expect(page.getByRole('heading',{name:/고개 숙여라/})).toBeVisible();await page.getByRole('button',{name:'옵션 열기'}).click();await page.getByRole('button',{name:'접근성',exact:true}).click();const toggle=page.getByRole('switch',{name:'고대비 UI'});await toggle.click();await expect(toggle).toHaveAttribute('aria-checked','true');await page.keyboard.press('Escape');await page.reload();await expect(page.locator('html')).toHaveClass(/high-contrast/);});
test('tab inactivity immediately pauses the audio timeline',async({page})=>{await page.goto('/');await page.getByRole('button',{name:'기자회견 시작',exact:true}).click();await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'));});await expect(page.getByRole('heading',{name:'기자회견 일시정지'})).toBeVisible();});
test('keyboard-only assisted full stage',async({page})=>{await page.addInitScript(()=>{localStorage.setItem('pr-panic-profile-v1',JSON.stringify({state:{options:{volume:0,latency:0,reducedMotion:true,reducedFlash:true,particles:false,visualBeat:true,audioBeat:true,assist:true,snap:true,highContrast:false,mirror:false,subtitleSize:18,keys:['a','s','d']},best:{},cleared:[],collection:[]},version:0}));});await page.goto('/');await page.getByRole('button',{name:'기자회견 시작',exact:true}).focus();await page.keyboard.press('Enter');let last=-1;while(await page.getByRole('heading',{name:'기자회견 생존!'}).count()===0){const cue=await page.evaluate(async()=>{const {engine}=await import('/src/game/engine.ts');const e=engine.stage?.events[engine.state.eventIndex];return {index:engine.state.eventIndex,remaining:e?e.beat*60/engine.stage!.bpm-engine.state.elapsed:999,status:engine.state.status};});if(cue.status==='result')break;if(cue.index!==last&&cue.remaining<.03&&cue.remaining>-.1){await page.keyboard.press('Space');last=cue.index;}await page.waitForTimeout(10);}await expect(page.getByRole('heading',{name:'기자회견 생존!'})).toBeVisible();});
for(const width of [390,768,1440])test(`responsive page fits ${width}px`,async({page})=>{await page.setViewportSize({width,height:900});await page.goto('/');await expect(page.getByRole('button',{name:'기자회견 시작',exact:true})).toBeInViewport();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();const primary=await page.getByRole('button',{name:'기자회견 시작',exact:true}).boundingBox();const guide=await page.getByRole('button',{name:'어떻게 사과하나요?'}).boundingBox();expect(primary&&guide&&(primary.x+primary.width<=guide.x+1||primary.y+primary.height<=guide.y+1||guide.x+guide.width<=primary.x+1)).toBeTruthy();});
test('reduced motion is inherited from browser preference',async({page})=>{await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/');await expect(page.locator('html')).toHaveClass(/reduce-motion/);});
test('semantic main and modal accessibility',async({page})=>{await page.goto('/');const result=await new AxeBuilder({page}).withRules(['button-name','html-has-lang','document-title','landmark-one-main','image-alt']).analyze();expect(result.violations).toEqual([]);await page.getByRole('button',{name:'어떻게 사과하나요?'}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);});
test('PWA shell can reload offline after cache installation',async({page,context})=>{await page.goto('/');await page.evaluate(async()=>{await navigator.serviceWorker.ready;});await page.reload();await page.waitForTimeout(1500);await context.setOffline(true);await page.reload();await expect(page.getByRole('button',{name:'기자회견 시작',exact:true})).toBeVisible();await context.setOffline(false);});
