import {useEffect,useRef,useState,useSyncExternalStore} from 'react';
import {ArrowLeft,Pause,Play,RotateCcw,Settings,Target,Volume2,VolumeX,ScanLine,Keyboard,MoveDown,Heart,ChevronRight} from 'lucide-react';
import {engine} from '../game/engine';
import {stages,type Stage} from '../game/core';
import {useProfile} from '../game/store';
import {useI18n, getLocalizedStage} from '../game/i18n';

import ManagerKim from './ManagerKim';
import PixiStage from './PixiStage';
export default function Game({stage,practice,onExit,onOptions,onNext}:{stage:Stage;practice:boolean;onExit:()=>void;onOptions:()=>void;onNext:(s:Stage)=>void}){const {t,lang}=useI18n();const localizedStage=getLocalizedStage(stage,lang);const s=useSyncExternalStore(engine.subscribe,engine.getSnapshot);const options=useProfile(p=>p.options);const setOption=useProfile(p=>p.setOption);const [debug,setDebug]=useState(false);const drag=useRef<{y:number;angle:number;swiped:boolean}|null>(null);const event=localizedStage.events[s.eventIndex];const target=event?.targetAngle??45;const total=localizedStage.events[localizedStage.events.length-1].beat+2;
 useEffect(()=>{const visibility=()=>{if(document.hidden)engine.pause();};const blur=()=>engine.pause();document.addEventListener('visibilitychange',visibility);window.addEventListener('blur',blur);const down=(e:KeyboardEvent)=>{if((e.target as HTMLElement).matches('input,textarea,select')||e.repeat)return;if(e.key==='Escape'){e.preventDefault();if(engine.state.status==='playing')engine.pause();else if(engine.state.status==='paused')void engine.resume();return;}if(engine.state.status!=='playing')return;const keys=useProfile.getState().options.keys;const i=keys.indexOf(e.key.toLowerCase());if(i>=0){e.preventDefault();engine.setAngle([45,90,120][i]);}if(e.key==='ArrowDown'){e.preventDefault();engine.down();}if(e.code==='Space'){e.preventDefault();if(useProfile.getState().options.assist)engine.submit();else if(engine.state.dogeza)engine.submit();else if(engine.state.angle>0)engine.submit();}};const up=(e:KeyboardEvent)=>{if(engine.state.status!=='playing')return;if(useProfile.getState().options.keys.includes(e.key.toLowerCase())){engine.submit();if(!engine.state.holding)engine.setAngle(0);}if(e.code==='Space'&&engine.state.dogeza&&!useProfile.getState().options.assist)engine.submit();else if(e.code==='Space'&&engine.state.holding)engine.setAngle(0);};window.addEventListener('keydown',down);window.addEventListener('keyup',up);return()=>{document.removeEventListener('visibilitychange',visibility);window.removeEventListener('blur',blur);window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);};},[]);
 const leave=()=>{engine.stop();onExit();};
 return <section className="game-page"><div className="game-page-heading"><button className="text-button" onClick={()=>{engine.pause();}}><ArrowLeft size={17}/> {t.common.backToLobby}</button><span>{practice?t.common.practiceNotice:`CHAPTER ${String(stage.chapter).padStart(2,'0')} / STAGE ${stage.id}`}</span><button className="icon-button" aria-label={t.common.pause} onClick={()=>engine.pause()}><Pause size={19}/></button></div>
 <div className="game-board"><div className="game-hud"><div className="trust-panel"><span><Heart size={14}/> {t.game.trustLabel}</span><strong>{s.trust}<small>%</small></strong><div className="trust-track"><i style={{width:`${s.trust}%`}}/></div></div><div className="question-panel"><span className="question-label"><i/> {event?.isFakeCue?t.game.fakeCueWarning:t.game.reporterAsking} <span>{t.game.questionNumber} {String(s.eventIndex+1).padStart(2,'0')}</span></span><p style={{fontSize:options.subtitleSize}}>{event?.question||t.game.finishNotice}</p>{event?.holdBeats&&<small>{t.game.holdInstruction(event.holdBeats)}</small>}</div><div className="score-panel"><span>{t.game.score}</span><strong>{String(s.score).padStart(6,'0')}</strong><small><b>{s.combo}</b> {t.game.combo}</small></div></div>
 <div className={`play-scene ${options.mirror?'mirrored':''}`} style={{backgroundImage:`url(/images/${stage.backgroundId}.jpg)`}} onPointerDown={e=>{if(s.status!=='playing')return;e.currentTarget.setPointerCapture(e.pointerId);drag.current={y:e.clientY,angle:s.angle,swiped:false};}} onPointerMove={e=>{if(!drag.current)return;const dy=e.clientY-drag.current.y;if(target==='dogeza'){if(dy>70&&!drag.current.swiped){drag.current.swiped=true;engine.down();}return;}engine.setAngle(drag.current.angle+dy*.65);}} onPointerUp={()=>{if(!drag.current)return;drag.current=null;if(target==='dogeza'&&!engine.state.dogeza)return;engine.submit();}} onPointerCancel={()=>{drag.current=null;}}>
 <PixiStage background={stage.backgroundId}/><div className="scene-label"><span className="live-dot"/> LIVE <b>{localizedStage.title}</b></div><div className="scene-tools"><button className={debug?'active':''} aria-label="자세 디버거 표시 전환" onPointerDown={e=>e.stopPropagation()} onClick={()=>setDebug(!debug)}><ScanLine size={17}/> {debug?'DEBUG ON':'DEBUG'}</button><button aria-label={options.volume?'소리 끄기':'소리 켜기'} onPointerDown={e=>e.stopPropagation()} onClick={()=>setOption('volume',options.volume?0:.5)}>{options.volume?<Volume2 size={18}/>:<VolumeX size={18}/>}</button></div>
 <div className="character-layer"><ManagerKim angle={typeof target==='number'?target:0} dogeza={target==='dogeza'} ghost/><ManagerKim angle={s.angle} dogeza={s.dogeza} target={typeof target==='number'?target:125} debug={debug}/></div>
 <div className={`judgement ${s.grade==='MISS'||s.grade==='성급한 사과'?'miss':''}`} key={`${s.judged}-${s.grade}`}><span>{s.grade==='PERFECT'?'✦ ':s.grade==='MISS'?'× ':''}{s.grade}</span>{s.judged>0&&<small>{s.error>0?'+':''}{Math.round(s.error)} ms</small>}</div>{s.combo>=20&&<div className="miracle">{t.game.miracle}</div>}
 <div className="angle-readout"><small>CURRENT ANGLE</small><strong>{s.dogeza?t.game.dogeza:`${Math.round(s.angle)}°`}</strong><span>{t.game.currentPose}</span></div><div className="target-readout"><small><Target size={13}/> TARGET ANGLE</small><strong>{target==='dogeza'?t.game.dogeza:`${target}°`}</strong><span>{event?.isFakeCue?t.game.doNotBow:event?.holdBeats?t.game.holdInstruction(event.holdBeats):t.game.bowOnLastBeat}</span></div>
 {s.countdown>0&&s.status==='playing'&&<div className="countdown-overlay"><small>{t.game.countdownBreath}</small><strong>{s.countdown}</strong><span>{t.game.countdownBow}</span></div>}
 </div>
 <div className="rhythm-section"><div className="bpm-block"><strong>{stage.bpm}</strong><span>BPM</span></div><div className="rhythm-lane"><div className="lane-line"/><div className="hit-line"><span>{t.game.hitLineLabel}</span></div>{options.visualBeat&&Array.from({length:18},(_,i)=>{const b=Math.floor(s.beat)-2+i;const x=20+(b-s.beat)*10;return <i key={b} className={`beat-mark ${b%4===0?'major':''}`} style={{left:`${x}%`}}/>;})}{stage.events.map((e,i)=>{const x=20+(e.beat-s.beat)*10;return x>-10&&x<110?<div key={e.id} className={`rhythm-note ${e.isFakeCue?'fake':''} ${i<s.eventIndex?'judged':''}`} style={{left:`${x}%`}}><span>{e.isFakeCue?'?':e.targetAngle==='dogeza'?'↓':`${e.targetAngle}°`}</span>{!!e.holdBeats&&<i style={{width:`${e.holdBeats*70}px`}}/>}</div>:null;})}</div><div className="time-block">{Math.min(100,Math.max(0,Math.round(s.beat/total*100)))}<small>%</small></div></div>
 <div className="game-controls"><span><Keyboard size={17}/> {options.assist?t.game.assistModeNotice:t.options.input.inputGuide.split('\n')[0]}</span><div>{[45,90,120].map((a,i)=><button key={a} onPointerDown={e=>{e.stopPropagation();engine.setAngle(a);}} onPointerUp={()=>engine.submit()}><kbd>{options.keys[i].toUpperCase()}</kbd>{a}°</button>)}<button onClick={()=>{if(options.assist)engine.submit();else {engine.down();engine.down();}}}><kbd>↓↓</kbd>{t.game.dogeza}</button><button onPointerDown={()=>engine.submit()}><kbd>SPACE</kbd>{t.game.holdConfirm}</button></div></div></div>
 <div className="game-footnote"><span><MoveDown size={15}/> {t.game.touchGuide}</span><span>판정 오차 ±45ms · 각도 ±4° <b>{t.game.fairApology}</b></span></div>
 {(s.status==='paused'||s.status==='result')&&<div className="modal-shade"><div className={`paper-modal result-modal ${s.status==='result'?'result-paper':''}`} role="dialog" aria-modal="true" aria-label={s.status==='paused'?t.common.pause:t.game.resultEyebrow}><span className="eyebrow">{s.status==='paused'?t.game.pausedEyebrow:t.game.resultEyebrow}</span><h2>{s.status==='paused'?t.game.pausedTitle:s.trust>0?t.game.survivedTitle:t.game.panicTitle}</h2>{s.status==='result'?<><div className="result-stamp">{s.trust>0?t.game.survivedStamp:t.game.panicStamp}</div><p>{s.trust>0?t.game.survivedDesc:t.game.panicDesc}</p><div className="result-stats"><div><span>{t.game.finalScore}</span><strong>{s.score.toLocaleString()}</strong></div><div><span>{t.game.maxCombo}</span><strong>{s.maxCombo}</strong></div><div><span>{t.game.accuracy}</span><strong>{Math.round(s.accuracy/Math.max(1,s.judged)*100)}%</strong></div></div><span className="muted">{options.assist?t.game.assistModeNotice:t.game.normalModeNotice} · {t.game.savedNotice}</span></>:<p>{t.game.pausedDesc.split('\n').map((line,idx)=><span key={idx}>{line}<br/></span>)}</p>}
 <div className="modal-action-stack">{s.status==='paused'?<button className="red-button" onClick={()=>void engine.resume()}><Play size={18}/> {t.common.resume}</button>:s.trust>0&&Number(stage.id)<30&&<button className="red-button" onClick={()=>onNext(stages[Number(stage.id)])}>{t.common.nextStage} <ChevronRight size={19}/></button>}<button className="outline-button" onClick={()=>void engine.start(stage,practice)}><RotateCcw size={17}/> {t.common.retry}</button>{s.status==='paused'&&<button className="outline-button" onClick={onOptions}><Settings size={17}/> {t.common.options}</button>}<button className="text-button" onClick={leave}><ArrowLeft size={16}/> {t.common.backToLobby}</button></div></div></div>}
 </section>;
}
