import {useEffect,useRef,useState,useSyncExternalStore} from 'react';
import {ArrowLeft,Pause,Play,RotateCcw,Settings,Target,Volume2,VolumeX,ScanLine,Keyboard,MoveDown,Heart,ChevronRight} from 'lucide-react';
import {engine} from '../game/engine';
import {stages,type Stage} from '../game/core';
import {useProfile} from '../game/store';

import ManagerKim from './ManagerKim';
import PixiStage from './PixiStage';
export default function Game({stage,practice,onExit,onOptions,onNext}:{stage:Stage;practice:boolean;onExit:()=>void;onOptions:()=>void;onNext:(s:Stage)=>void}){const s=useSyncExternalStore(engine.subscribe,engine.getSnapshot);const options=useProfile(p=>p.options);const setOption=useProfile(p=>p.setOption);const [debug,setDebug]=useState(false);const drag=useRef<{y:number;angle:number;swiped:boolean}|null>(null);const event=stage.events[s.eventIndex];const target=event?.targetAngle??45;const total=stage.events[stage.events.length-1].beat+2;
 useEffect(()=>{const visibility=()=>{if(document.hidden)engine.pause();};const blur=()=>engine.pause();document.addEventListener('visibilitychange',visibility);window.addEventListener('blur',blur);const down=(e:KeyboardEvent)=>{if((e.target as HTMLElement).matches('input,textarea,select')||e.repeat)return;if(e.key==='Escape'){e.preventDefault();if(engine.state.status==='playing')engine.pause();else if(engine.state.status==='paused')void engine.resume();return;}if(engine.state.status!=='playing')return;const keys=useProfile.getState().options.keys;const i=keys.indexOf(e.key.toLowerCase());if(i>=0){e.preventDefault();engine.setAngle([45,90,120][i]);}if(e.key==='ArrowDown'){e.preventDefault();engine.down();}if(e.code==='Space'){e.preventDefault();if(useProfile.getState().options.assist)engine.submit();else if(engine.state.dogeza)engine.submit();else if(engine.state.angle>0)engine.submit();}};const up=(e:KeyboardEvent)=>{if(engine.state.status!=='playing')return;if(useProfile.getState().options.keys.includes(e.key.toLowerCase())){engine.submit();if(!engine.state.holding)engine.setAngle(0);}if(e.code==='Space'&&engine.state.dogeza&&!useProfile.getState().options.assist)engine.submit();else if(e.code==='Space'&&engine.state.holding)engine.setAngle(0);};window.addEventListener('keydown',down);window.addEventListener('keyup',up);return()=>{document.removeEventListener('visibilitychange',visibility);window.removeEventListener('blur',blur);window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);};},[]);
 const leave=()=>{engine.stop();onExit();};
 return <section className="game-page"><div className="game-page-heading"><button className="text-button" onClick={()=>{engine.pause();}}><ArrowLeft size={17}/> 기자회견 대기실</button><span>{practice?'연습실 · 점수에 반영되지 않습니다':`CHAPTER ${String(stage.chapter).padStart(2,'0')} / STAGE ${stage.id}`}</span><button className="icon-button" aria-label="일시정지" onClick={()=>engine.pause()}><Pause size={19}/></button></div>
 <div className="game-board"><div className="game-hud"><div className="trust-panel"><span><Heart size={14}/> 국민 신뢰도</span><strong>{s.trust}<small>%</small></strong><div className="trust-track"><i style={{width:`${s.trust}%`}}/></div></div><div className="question-panel"><span className="question-label"><i/> {event?.isFakeCue?'함정 질문 · 아직 숙이지 마세요':'기자가 묻습니다'} <span>Q. {String(s.eventIndex+1).padStart(2,'0')}</span></span><p style={{fontSize:options.subtitleSize}}>{event?.question||'오늘 기자회견은 여기까지입니다.'}</p>{event?.holdBeats&&<small>{event.holdBeats}박자 동안 자세를 유지하세요</small>}</div><div className="score-panel"><span>SCORE</span><strong>{String(s.score).padStart(6,'0')}</strong><small><b>{s.combo}</b> COMBO</small></div></div>
 <div className={`play-scene ${options.mirror?'mirrored':''}`} style={{backgroundImage:`url(/images/${stage.backgroundId}.jpg)`}} onPointerDown={e=>{if(s.status!=='playing')return;e.currentTarget.setPointerCapture(e.pointerId);drag.current={y:e.clientY,angle:s.angle,swiped:false};}} onPointerMove={e=>{if(!drag.current)return;const dy=e.clientY-drag.current.y;if(target==='dogeza'){if(dy>70&&!drag.current.swiped){drag.current.swiped=true;engine.down();}return;}engine.setAngle(drag.current.angle+dy*.65);}} onPointerUp={()=>{if(!drag.current)return;drag.current=null;if(target==='dogeza'&&(!engine.state.dogeza||audioNowTooEarly()))return;engine.submit();}} onPointerCancel={()=>{drag.current=null;}}>
 <PixiStage background={stage.backgroundId}/><div className="scene-label"><span className="live-dot"/> LIVE <b>{stage.title}</b></div><div className="scene-tools"><button className={debug?'active':''} aria-label="자세 디버거 표시 전환" onPointerDown={e=>e.stopPropagation()} onClick={()=>setDebug(!debug)}><ScanLine size={17}/> {debug?'DEBUG ON':'DEBUG'}</button><button aria-label={options.volume?'소리 끄기':'소리 켜기'} onPointerDown={e=>e.stopPropagation()} onClick={()=>setOption('volume',options.volume?0:.5)}>{options.volume?<Volume2 size={18}/>:<VolumeX size={18}/>}</button></div>
 <div className="character-layer"><ManagerKim angle={typeof target==='number'?target:0} dogeza={target==='dogeza'} ghost/><ManagerKim angle={s.angle} dogeza={s.dogeza} target={typeof target==='number'?target:125} debug={debug}/></div>
 <div className={`judgement ${s.grade==='MISS'||s.grade==='성급한 사과'?'miss':''}`} key={`${s.judged}-${s.grade}`}><span>{s.grade==='PERFECT'?'✦ ':s.grade==='MISS'?'× ':''}{s.grade}</span>{s.judged>0&&<small>{s.error>0?'+':''}{Math.round(s.error)} ms</small>}</div>{s.combo>=20&&<div className="miracle">🌈 기적의 사과</div>}
 <div className="angle-readout"><small>CURRENT ANGLE</small><strong>{s.dogeza?'도게자':`${Math.round(s.angle)}°`}</strong><span>현재 자세</span></div><div className="target-readout"><small><Target size={13}/> TARGET ANGLE</small><strong>{target==='dogeza'?'도게자':`${target}°`}</strong><span>{event?.isFakeCue?'× 절하지 마세요':event?.holdBeats?`${event.holdBeats}박자 유지`:'마지막 박자에 사과!'}</span></div>
 {s.countdown>0&&s.status==='playing'&&<div className="countdown-overlay"><small>심호흡하세요, 김부장.</small><strong>{s.countdown}</strong><span>박자에 맞춰 고개를 숙이세요</span></div>}
 </div>
 <div className="rhythm-section"><div className="bpm-block"><strong>{stage.bpm}</strong><span>BPM</span></div><div className="rhythm-lane"><div className="lane-line"/><div className="hit-line"><span>사과!</span></div>{options.visualBeat&&Array.from({length:18},(_,i)=>{const b=Math.floor(s.beat)-2+i;const x=20+(b-s.beat)*10;return <i key={b} className={`beat-mark ${b%4===0?'major':''}`} style={{left:`${x}%`}}/>;})}{stage.events.map((e,i)=>{const x=20+(e.beat-s.beat)*10;return x>-10&&x<110?<div key={e.id} className={`rhythm-note ${e.isFakeCue?'fake':''} ${i<s.eventIndex?'judged':''}`} style={{left:`${x}%`}}><span>{e.isFakeCue?'?':e.targetAngle==='dogeza'?'↓':`${e.targetAngle}°`}</span>{!!e.holdBeats&&<i style={{width:`${e.holdBeats*70}px`}}/>}</div>:null;})}</div><div className="time-block">{Math.min(100,Math.max(0,Math.round(s.beat/total*100)))}<small>%</small></div></div>
 <div className="game-controls"><span><Keyboard size={17}/> {options.assist?'보조 모드 · Space 한 번으로 자세 확정':'누르고 자세를 맞춘 뒤, 박자에 맞춰 놓으세요'}</span><div>{[45,90,120].map((a,i)=><button key={a} onPointerDown={e=>{e.stopPropagation();engine.setAngle(a);}} onPointerUp={()=>engine.submit()}><kbd>{options.keys[i].toUpperCase()}</kbd>{a}°</button>)}<button onClick={()=>{if(options.assist)engine.submit();else {engine.down();engine.down();}}}><kbd>↓↓</kbd>도게자</button><button onPointerDown={()=>engine.submit()}><kbd>SPACE</kbd>유지 / 확정</button></div></div></div>
 <div className="game-footnote"><span><MoveDown size={15}/> 터치 · 김부장을 아래로 드래그해 사과 각도를 조절하세요.</span><span>판정 오차 ±45ms · 각도 ±4° <b>공정한 사과를 지향합니다.</b></span></div>
 {(s.status==='paused'||s.status==='result')&&<div className="modal-shade"><div className={`paper-modal result-modal ${s.status==='result'?'result-paper':''}`} role="dialog" aria-modal="true" aria-label={s.status==='paused'?'일시정지':'기자회견 결과'}><span className="eyebrow">{s.status==='paused'?'잠시만요, 물 한 잔만…':'OFFICIAL PRESS REPORT'}</span><h2>{s.status==='paused'?'기자회견 일시정지':s.trust>0?'기자회견 생존!':'PR 대참사'}</h2>{s.status==='result'?<><div className="result-stamp">{s.trust>0?'SURVIVED':'PANIC!'}</div><p>{s.trust>0?'오늘도 무사히 고개를 숙였습니다. 퇴근하세요, 김부장.':'괜찮습니다. 사과할 기회는 또 있으니까요.'}</p><div className="result-stats"><div><span>최종 점수</span><strong>{s.score.toLocaleString()}</strong></div><div><span>최대 콤보</span><strong>{s.maxCombo}</strong></div><div><span>정확도</span><strong>{Math.round(s.accuracy/Math.max(1,s.judged)*100)}%</strong></div></div><span className="muted">{options.assist?'한 버튼 보조 모드 · 별도 기록':'일반 모드'} · 진행 상황 자동 저장됨</span></>:<p>질문도, 박자도 잠깐 멈췄습니다.<br/>재개하면 3박자 카운트다운 후 이어집니다.</p>}
 <div className="modal-action-stack">{s.status==='paused'?<button className="red-button" onClick={()=>void engine.resume()}><Play size={18}/> 기자회견 재개</button>:s.trust>0&&Number(stage.id)<30&&<button className="red-button" onClick={()=>onNext(stages[Number(stage.id)])}>다음 기자회견 <ChevronRight size={19}/></button>}<button className="outline-button" onClick={()=>void engine.start(stage,practice)}><RotateCcw size={17}/> 다시 도전</button>{s.status==='paused'&&<button className="outline-button" onClick={onOptions}><Settings size={17}/> 옵션</button>}<button className="text-button" onClick={leave}><ArrowLeft size={16}/> 대기실로 돌아가기</button></div></div></div>}
 </section>;
}
