import {useCallback,useEffect,useState} from 'react';
import {ArrowRight,ArrowUpRight,AudioLines,BookOpen,Check,ChevronRight,CircleHelp,Clock3,Gamepad2,Headphones,Keyboard,LockKeyhole,Megaphone,Mic2,MousePointer2,Play,Radio,Settings2,ShieldCheck,Sparkles,Trophy,Zap} from 'lucide-react';
import {stages,projectiles,type Stage} from './game/core';
import {engine} from './game/engine';
import {useProfile} from './game/store';
import Game from './components/Game';
import ManagerKim from './components/ManagerKim';
import {Modal,OptionsPanel,Calibration,HowTo,Editor} from './components/Dialogs';
type Dialog='options'|'calibration'|'howto'|'about'|'credits'|'editor'|null;
type View='home'|'stages'|'game'|'collection';
export default function App(){const [view,setView]=useState<View>('home');const [dialog,setDialog]=useState<Dialog>(null);const [stage,setStage]=useState<Stage>(stages[0]);const [practice,setPractice]=useState(false);const [chapter,setChapter]=useState(0);const [collectInfo,setCollectInfo]=useState<number|null>(null);const profile=useProfile();const {options,cleared,best,collection}=profile;const closeDialog=useCallback(()=>setDialog(null),[]);const start=async(s:Stage=stage,training=false)=>{setDialog(null);setStage(s);setPractice(training);await engine.start(s,training);setView('game');window.scrollTo({top:0,behavior:'instant'});};const navigate=(v:View)=>{if(view==='game')engine.stop();setView(v);window.scrollTo({top:0,behavior:'instant'});};useEffect(()=>{document.documentElement.classList.toggle('reduce-motion',options.reducedMotion);document.documentElement.classList.toggle('high-contrast',options.highContrast);},[options.reducedMotion,options.highContrast]);useEffect(()=>{if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});return()=>engine.stop();},[]);
 const nextStage=stages[Math.min(29,cleared.length)];
 const card=(s:Stage,compact=false)=><article key={s.id} className={`stage-card ${stage.id===s.id?'chosen':''} ${compact?'compact':''}`}><button className="stage-art" aria-label={`${s.title} 플레이`} onClick={()=>void start(s)} style={{backgroundImage:`url(/images/${s.id==='01'?'press-room':s.backgroundId}.jpg)`}}><span className="stage-number">{s.id}</span><span className="stage-difficulty">{s.difficulty===1?'입문':s.difficulty===2?'초급':s.difficulty===3?'중급':s.difficulty===4?'상급':'극한'} <span>{Array.from({length:Math.min(5,s.difficulty)},()=> '■').join('')}</span></span>{cleared.includes(s.id)?<span className="clear-badge"><Check size={12}/> CLEAR</span>:s.id==='01'&&<span className="recommend-badge">첫 출근 추천</span>}<span className="art-play"><Play size={25} fill="currentColor"/></span></button><div className="stage-info"><div className="stage-info-top"><span>STAGE {s.id}</span><span><AudioLines size={12}/> {s.bpm} BPM</span></div><button className="stage-title-button" onClick={()=>{setStage(s);void start(s);}}><h3>{s.title}</h3><ArrowUpRight size={18}/></button><p>{s.id==='01'?'복사기가 사고 쳤다. 사과는 내 몫이다.':s.id==='02'?'커피 자판기의 독립 선언, 본사 비상.':s.id==='03'?'쏟아지는 빗줄기, 쏟아지는 질문.':`챕터 ${s.chapter} · 더 복잡해지는 질문에 대비하세요.`}</p><div className="stage-bottom"><span><Clock3 size={12}/> 약 {Math.ceil((s.events[s.events.length-1].beat+5)*60/s.bpm)}초</span><span>{best[s.id]?`BEST ${best[s.id].toLocaleString()}`:s.id==='01'?'45° · 90° · 120°':s.id==='02'?'홀드 · 함정 질문':'엇박 · 도게자'}</span></div></div></article>;
 return <div className="app-shell"><div className="edition-bar"><span><i/> THE DAILY APOLOGY <b>매일 사과하는 사람들을 위한 신문</b></span><span>모든 사건은 허구입니다. 사과만큼은 진심입니다. <span className="edition-no">VOL. 001</span></span></div>
 <header className="main-header"><button className="brand" aria-label="PR PANIC 대기실 홈" onClick={()=>navigate('home')}><span className="brand-icon"><Megaphone size={30} strokeWidth={2.2}/><i>!</i></span><span><strong>PR PANIC<span>®</span></strong><small>공식 사과 시뮬레이터</small></span></button><nav aria-label="주 메뉴"><button className={view==='home'?'active':''} onClick={()=>navigate('home')}><Radio size={15}/> 대기실</button><button className={view==='stages'?'active':''} onClick={()=>navigate('stages')}>스테이지</button><button className={view==='game'&&practice?'active':''} onClick={()=>void start(stages[0],true)}>연습실</button><button className={view==='collection'?'active':''} onClick={()=>navigate('collection')}>수난 도감 <span>{collection.length.toString().padStart(2,'0')}</span></button></nav><div className="header-right"><span className="save-status"><i/> 로컬 저장됨</span><button className="icon-button settings-button" aria-label="옵션 열기" onClick={()=>{if(view==='game')engine.pause();setDialog('options');}}><Settings2 size={21}/></button></div></header>
 <main>{view==='game'?<Game stage={stage} practice={practice} onExit={()=>setView('home')} onOptions={()=>setDialog('options')} onNext={s=>void start(s)}/>:view==='home'?<>
 <div className="front-page-heading"><span><span className="red-label">긴급 속보</span> 오늘도 누군가는 사과해야 한다.</span><span><span className="live-dot"/> 기자회견 개장 <b>ON AIR</b></span></div>
 <section className="hero"><div className="hero-art"/><div className="hero-paper"/><div className="hero-copy"><div className="hero-kicker"><span>공격 불가.</span> 변명 불가. <b>퇴근은 가능할까?</b></div><h1>고개 숙여라.<br/><span>살아남아라.</span></h1><p>질문은 쏟아지고, 박자는 멈추지 않는다.<br/>당신의 유일한 무기는 <b>정확한 타이밍의 사과.</b></p><div className="hero-buttons"><button className="red-button start-button" onClick={()=>void start(cleared.length?nextStage:stages[0])}><Mic2 size={21}/>{cleared.length?'다음 기자회견 시작':'기자회견 시작'}<ArrowRight size={21}/></button><button className="howto-button" onClick={()=>setDialog('howto')}><CircleHelp size={16}/> 어떻게 사과하나요?</button></div><div className="hero-platforms"><span><Keyboard size={14}/> 키보드</span><i/><span><MousePointer2 size={14}/> 마우스 & 터치</span><i/><span><Gamepad2 size={15}/> 게임패드</span></div></div><div className="live-stamp"><span><i/> LIVE</span><small>긴급 기자회견</small></div><button className="character-tag" onClick={()=>setDialog('about')}><span>오늘의 사과 담당</span><strong>김부장 <ArrowUpRight size={17}/></strong><small>잘못은 회사가, 사과는 내가.</small></button><div className="hero-corner">100% FICTION. 120° APOLOGY.</div></section>
 <div className="news-ticker"><span className="ticker-title"><Zap size={15} fill="currentColor"/> 속보</span><div><b>“사내 커피 자판기, 독립 선언”</b><span>본사 측 “원두부터 확인 중”</span><i>✦</i><b>복사기, 직원 비밀 일기 300부 무단 출력</b><span>김부장 긴급 소환</span></div><span className="ticker-end">계속되는 위기, 계속되는 사과 <ArrowRight size={15}/></span></div>
 <section className="daily-section"><div className="section-heading"><div><span className="section-index">01 /</span><h2>오늘의 기자회견</h2><span className="section-subtitle">작은 사과부터, 우주급 사과까지.</span></div><button className="text-button" onClick={()=>navigate('stages')}>전체 30개 스테이지 <ArrowRight size={15}/></button></div><div className="daily-grid"><div className="stage-grid">{stages.slice(0,3).map(s=>card(s))}</div><aside className="field-guide"><div className="guide-label"><BookOpen size={16}/><span>김부장의 생존 수첩</span><span>TIP #01</span></div><h3>잘 숙이는 것도<br/><span>능력입니다.</span><span className="guide-spark">✳</span></h3><div className="guide-diagram"><span className="diagram-person">◉<i/></span><span className="diagram-arc"/><b>90°</b><span className="diagram-baseline"/><small>진심은 수평으로.</small></div><p>각도는 정확하게, 타이밍은 칼같이.<br/>일단 연습실에서 허리부터 풀어보세요.</p><button onClick={()=>void start(stages[0],true)}>연습실로 가기 <ArrowRight size={17}/></button></aside></div></section>
 <div className="bottom-strip"><div><ShieldCheck size={20}/><span><b>반격 없는 리듬 액션</b><small>맞서지 마세요. 박자에 맞춰 숙이세요.</small></span></div><div><Headphones size={20}/><span><b>이어폰 착용 권장</b><small>사과는 타이밍이 생명입니다.</small></span><button onClick={()=>setDialog('calibration')}>오디오 보정 <ArrowUpRight size={12}/></button></div><div><AccessibilityIcon/><span><b>누구나 사과할 수 있도록</b><small>한 버튼 모드와 다양한 접근성 옵션.</small></span><button onClick={()=>setDialog('options')}>옵션 <ArrowUpRight size={12}/></button></div></div>
 </>:view==='stages'?<section className="browse-page"><div className="page-title"><div><span className="eyebrow">30 PLACES TO SAY SORRY</span><h1>기자회견 일정표<span>스테이지 선택</span></h1><p>동네 지점에서 우주까지. 김부장의 사과는 끝나지 않습니다.</p></div><div className="progress-stamp"><Trophy size={24}/><strong>{cleared.length}<small> / 30</small></strong><span>기자회견 생존</span></div></div><div className="chapter-tabs">{['전체 일정','첫 출근','본사 비상','시스템 오류','극한 출장','지구 밖 사과','마지막 질문'].map((c,i)=><button className={chapter===i?'selected':''} key={c} onClick={()=>setChapter(i)}>{i>0&&<small>CH.{i}</small>}{c}</button>)}</div><p className="sample-note"><Sparkles size={15}/> 01–03은 전용 입문 스테이지입니다. 04–30은 확장 샘플 패턴이며, 모든 스테이지를 자유롭게 플레이할 수 있습니다.</p><div className="browse-grid">{stages.filter(s=>chapter===0||s.chapter===chapter).map(s=>card(s,true))}</div></section>:<section className="browse-page"><div className="page-title"><div><span className="eyebrow">THE MUSEUM OF PUBLIC OPINION</span><h1>수난 도감<span>맞은 만큼 배운다.</span></h1><p>기자회견에서 만난 18가지 무해한 재앙. 전부 만화 소품이니 안심하세요.</p></div><div className="progress-stamp"><BookOpen size={24}/><strong>{collection.length}<small> / 18</small></strong><span>수집한 수난</span></div></div><div className="collection-grid">{projectiles.map(([emoji,title,description,flight],i)=><button key={title} className={`collection-card ${collection.includes(i)?'unlocked':'locked'}`} onClick={()=>setCollectInfo(i)}><span className="collection-number">NO. {String(i+1).padStart(2,'0')}</span><span className="projectile-emoji">{collection.includes(i)?emoji:<LockKeyhole size={34}/>}</span><h3>{collection.includes(i)?title:'아직 만나지 않은 수난'}</h3><p>{collection.includes(i)?description:'플레이 중 한 번 맞으면 기록됩니다.'}</p><span className="flight-type">{collection.includes(i)?flight:'미발견'} <ChevronRight size={12}/></span></button>)}</div></section>}</main>
 <footer><div className="footer-brand"><Megaphone size={18}/><b>PR PANIC</b><span>허구의 회사. 진짜 같은 식은땀.</span></div><div><button onClick={()=>setDialog('about')}>김부장 소개</button><span>·</span><button onClick={()=>setDialog('editor')}>비트맵 편집기</button><span>·</span><button onClick={()=>setDialog('credits')}>크레딧</button><span className="footer-version">© 2026 PR PANIC · v1.0</span></div></footer>
 {dialog&&<Modal title={dialog==='options'?'사과 환경 설정':dialog==='calibration'?'당신의 박자를 찾으세요.':dialog==='howto'?'사과에도 요령이 있습니다.':dialog==='about'?'김부장을 소개합니다.':dialog==='editor'?'나만의 기자회견': '오늘도 고생하셨습니다.'} kicker={dialog==='options'?'MAKE YOURSELF COMFORTABLE':dialog==='editor'?'BEATMAP EDITOR':'OFFICIAL APOLOGY MANUAL'} onClose={closeDialog} wide={dialog==='howto'||dialog==='editor'}>{dialog==='options'?<OptionsPanel onCalibrate={()=>setDialog('calibration')}/>:dialog==='calibration'?<Calibration/>:dialog==='howto'?<HowTo/>:dialog==='editor'?<Editor onPlay={s=>void start(s)}/>:dialog==='about'?<div className="about-content"><div className="about-portrait"><ManagerKim/><span>사원증에는 아무 글자도 없다.</span></div><div className="about-tag">위기관리팀 · 만년 부장</div><h3>“죄송합니다! …무슨 일이죠?”</h3><p>사건의 전말은 몰라도 사과 각도는 정확한 사람.<br/>겁은 많지만 직업정신만큼은 이상할 정도로 강합니다.<br/>누군가 사고를 치면, 오늘도 김부장이 무대에 섭니다.</p><div className="notice-box">완전히 허구인 인물입니다. 실제 인물·회사·사건과 무관하며, 그 어떤 대상의 로고도 사용하지 않습니다.</div></div>:<div className="credits-content"><div className="credit-illustration"><Mic2 size={54}/><span>THANK YOU<br/>FOR APOLOGIZING.</span></div><p>모든 기자회견의 뒤에는<br/>아무 잘못 없이 고개를 숙이는 누군가가 있습니다.</p><hr/><h3>공식 사과 시뮬레이터: PR PANIC</h3><p>오리지널 코미디 리듬 액션 · 2026<br/>기획 · 코드 · 아트 디렉션 — PR PANIC 프로젝트<br/>음악 — Web Audio 절차적 재즈 루프<br/>일러스트 — 오리지널 AI 제작 배경<br/>React · PixiJS · XState · Zustand · Zod · Dexie</p><small>유혈, 상처, 공격 없는 100% 허구의 슬랩스틱 게임.</small><button className="red-button" onClick={closeDialog}>내일도 잘 부탁드립니다. <Check size={17}/></button></div>}</Modal>}
 {collectInfo!==null&&<Modal title={collection.includes(collectInfo)?projectiles[collectInfo][1]:'미발견 수난'} kicker={`FIELD COLLECTION / NO. ${String(collectInfo+1).padStart(2,'0')}`} onClose={()=>setCollectInfo(null)}><div className="item-detail"><span>{collection.includes(collectInfo)?projectiles[collectInfo][0]:'?'}</span><p>{collection.includes(collectInfo)?projectiles[collectInfo][2]:'기자회견에서 이 물건을 만나면 정체가 공개됩니다.'}</p><small>{collection.includes(collectInfo)?`비행 방식: ${projectiles[collectInfo][3]} · 무해한 만화 소품`:'정확한 사과도 좋지만, 가끔의 실수도 기록이 됩니다.'}</small><button className="outline-button" onClick={()=>{setCollectInfo(null);void start(stage);}}>기자회견으로 <ArrowRight size={16}/></button></div></Modal>}
 </div>;
}
function AccessibilityIcon(){return <svg width="23" height="23" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7"><circle cx="12" cy="4" r="2"/><path d="M4 8L12 10 20 8M12 10V15M12 15L7 22M12 15L17 22"/></svg>}
