import {useCallback,useEffect,useState} from 'react';
import {ArrowRight,ArrowUpRight,AudioLines,BookOpen,Check,ChevronRight,CircleHelp,Clock3,Gamepad2,Headphones,Keyboard,LockKeyhole,Megaphone,Mic2,MousePointer2,Play,Radio,Settings2,ShieldCheck,Sparkles,Trophy,Zap} from 'lucide-react';
import {stages,projectiles,type Stage} from './game/core';
import {engine} from './game/engine';
import {useProfile} from './game/store';
import {useI18n, getLocalizedStage, getLocalizedProjectile, type Language} from './game/i18n';
import Game from './components/Game';
import ManagerKim from './components/ManagerKim';
import {Modal,OptionsPanel,Calibration,HowTo,Editor} from './components/Dialogs';

type Dialog='options'|'calibration'|'howto'|'about'|'credits'|'editor'|null;
type View='home'|'stages'|'game'|'collection';

export default function App(){
  const {t,lang,setLanguage}=useI18n();
  const [view,setView]=useState<View>('home');
  const [dialog,setDialog]=useState<Dialog>(null);
  const [stage,setStage]=useState<Stage>(stages[0]);
  const [practice,setPractice]=useState(false);
  const [chapter,setChapter]=useState(0);
  const [collectInfo,setCollectInfo]=useState<number|null>(null);
  const profile=useProfile();
  const {options,cleared,best,collection}=profile;
  const closeDialog=useCallback(()=>setDialog(null),[]);
  const start=async(s:Stage=stage,training=false)=>{
    setDialog(null);
    setStage(s);
    setPractice(training);
    await engine.start(s,training);
    setView('game');
    window.scrollTo({top:0,behavior:'instant'});
  };
  const navigate=(v:View)=>{
    if(view==='game')engine.stop();
    setView(v);
    window.scrollTo({top:0,behavior:'instant'});
  };
  useEffect(()=>{
    document.documentElement.classList.toggle('reduce-motion',options.reducedMotion);
    document.documentElement.classList.toggle('high-contrast',options.highContrast);
  },[options.reducedMotion,options.highContrast]);
  useEffect(()=>{
    if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});
    return()=>engine.stop();
  },[]);

  const nextStage=stages[Math.min(29,cleared.length)];

  const card=(s:Stage,compact=false)=>{
    const locS=getLocalizedStage(s,lang);
    const estSec=Math.ceil((s.events[s.events.length-1].beat+5)*60/s.bpm);
    const diffLabel=s.difficulty===1?(lang==='ja'?'入門':lang==='en'?'Intro':'입문'):s.difficulty===2?(lang==='ja'?'初級':lang==='en'?'Beginner':'초급'):s.difficulty===3?(lang==='ja'?'中級':lang==='en'?'Mid':'중급'):s.difficulty===4?(lang==='ja'?'上級':lang==='en'?'Advanced':'상급'):(lang==='ja'?'極限':lang==='en'?'Extreme':'극한');
    const desc=s.id==='01'?(lang==='ja'?'コピー機が大暴走。お詫びは私の担当。':lang==='en'?'Copier leaked the diaries. Apologizing is my job.':'복사기가 사고 쳤다. 사과는 내 몫이다.'):s.id==='02'?(lang==='ja'?'コーヒー自販機の独立宣言、本社非常事態。':lang==='en'?'Coffee vending machine declared independence. HQ panic.':'커피 자판기의 독립 선언, 본사 비상.'):s.id==='03'?(lang==='ja'?'降りしきる雨、押し寄せる質問の嵐。':lang==='en'?'Pouring rain, pouring questions.':'쏟아지는 빗줄기, 쏟아지는 질문.'):lang==='ja'?`チャプター ${s.chapter} · ますます錯綜する質問に備えよ。`:lang==='en'?`Chapter ${s.chapter} · Prepare for escalating inquiries.`:`챕터 ${s.chapter} · 더 복잡해지는 질문에 대비하세요.`;

    return <article key={s.id} className={`stage-card ${stage.id===s.id?'chosen':''} ${compact?'compact':''}`}><button className="stage-art" aria-label={`${locS.title} 플레이`} onClick={()=>void start(s)} style={{backgroundImage:`url(/images/${s.id==='01'?'press-room':s.backgroundId}.jpg)`}}><span className="stage-number">{s.id}</span><span className="stage-difficulty">{diffLabel} <span>{Array.from({length:Math.min(5,s.difficulty)},()=>'■').join('')}</span></span>{cleared.includes(s.id)?<span className="clear-badge"><Check size={12}/> {t.browse.clearedBadge}</span>:s.id==='01'&&<span className="recommend-badge">{lang==='ja'?'初出勤おすすめ':lang==='en'?'RECOMMENDED':'첫 출근 추천'}</span>}<span className="art-play"><Play size={25} fill="currentColor"/></span></button><div className="stage-info"><div className="stage-info-top"><span>STAGE {s.id}</span><span><AudioLines size={12}/> {s.bpm} BPM</span></div><button className="stage-title-button" onClick={()=>{setStage(s);void start(s);}}><h3>{locS.title}</h3><ArrowUpRight size={18}/></button><p>{desc}</p><div className="stage-bottom"><span><Clock3 size={12}/> {lang==='ja'?`約 ${estSec}秒`:lang==='en'?`~${estSec}s`:`약 ${estSec}초`}</span><span>{best[s.id]?`BEST ${best[s.id].toLocaleString()}`:s.id==='01'?'45° · 90° · 120°':s.id==='02'?(lang==='ja'?'ホールド · 罠質問':lang==='en'?'Hold · Trick':'홀드 · 함정 질문'):(lang==='ja'?'裏拍 · 土下座':lang==='en'?'Syncopation · Dogeza':'엇박 · 도게자')}</span></div></div></article>;
  };

  return <div className="app-shell"><div className="edition-bar"><span><i/> THE DAILY APOLOGY <b>{lang==='ja'?'毎日お詫びする人々のための新聞':lang==='en'?'A Newspaper for Daily Apologizers':'매일 사과하는 사람들을 위한 신문'}</b></span><span>{lang==='ja'?'すべての事件はフィクションです。謝罪だけは本気です。':lang==='en'?'All incidents are fictional. The apologies are dead serious.':'모든 사건은 허구입니다. 사과만큼은 진심입니다.'} <span className="edition-no">VOL. 001</span></span></div>
  <header className="main-header"><button className="brand" aria-label="PR PANIC 대기실 홈" onClick={()=>navigate('home')}><span className="brand-icon"><Megaphone size={30} strokeWidth={2.2}/><i>!</i></span><span><strong>PR PANIC<span>®</span></strong><small>{lang==='ja'?'公式謝罪シミュレーター':lang==='en'?'Official Apology Simulator':'공식 사과 시뮬레이터'}</small></span></button><nav aria-label="주 메뉴"><button className={view==='home'?'active':''} onClick={()=>navigate('home')}><Radio size={15}/> {t.common.backToLobby}</button><button className={view==='stages'?'active':''} onClick={()=>navigate('stages')}>{t.nav.stages}</button><button className={view==='game'&&practice?'active':''} onClick={()=>void start(stages[0],true)}>{t.common.practice}</button><button className={view==='collection'?'active':''} onClick={()=>navigate('collection')}>{t.nav.collection} <span>{collection.length.toString().padStart(2,'0')}</span></button></nav><div className="header-right"><div className="lang-switcher" style={{display:'inline-flex',gap:'3px',alignItems:'center',marginRight:'6px'}}>{([['ko','KO'],['en','EN'],['ja','JA']] as const).map(([code,name])=><button key={code} className={`lang-pill ${lang===code?'selected':''}`} style={{fontSize:'11px',fontWeight:lang===code?'700':'500',padding:'3px 6px',borderRadius:'3px',border:'1px solid',borderColor:lang===code?'#bc4434':'#d1c7b7',backgroundColor:lang===code?'#bc4434':'transparent',color:lang===code?'#fff':'inherit',cursor:'pointer',lineHeight:1}} onClick={()=>setLanguage(code as Language)}>{name}</button>)}</div><span className="save-status"><i/> {t.game.savedNotice}</span><button className="icon-button settings-button" aria-label={t.options.title} onClick={()=>{if(view==='game')engine.pause();setDialog('options');}}><Settings2 size={21}/></button></div></header>
  <main>{view==='game'?<Game stage={stage} practice={practice} onExit={()=>setView('home')} onOptions={()=>setDialog('options')} onNext={s=>void start(s)}/>:view==='home'?<>
  <div className="front-page-heading"><span><span className="red-label">{t.hero.urgentNews}</span> {t.hero.urgentHeadline}</span><span><span className="live-dot"/> {t.hero.onAir}</span></div>
  <section className="hero"><div className="hero-art"/><div className="hero-paper"/><div className="hero-copy"><div className="hero-kicker">{t.hero.kicker}</div><h1>{t.hero.titleLine1}<br/><span>{t.hero.titleLine2}</span></h1><p>{t.hero.description.split('\n').map((line,idx)=><span key={idx}>{line}<br/></span>)}</p><div className="hero-buttons"><button className="red-button start-button" onClick={()=>void start(cleared.length?nextStage:stages[0])}><Mic2 size={21}/>{cleared.length?t.hero.startNext:t.hero.startFirst}<ArrowRight size={21}/></button><button className="howto-button" onClick={()=>setDialog('howto')}><CircleHelp size={16}/> {t.hero.howToPlay}</button></div><div className="hero-platforms"><span><Keyboard size={14}/> {t.hero.keyboard}</span><i/><span><MousePointer2 size={14}/> {t.hero.mouseTouch}</span><i/><span><Gamepad2 size={15}/> {t.hero.gamepad}</span></div></div><div className="live-stamp"><span><i/> LIVE</span><small>{t.hero.urgentConference}</small></div><button className="character-tag" onClick={()=>setDialog('about')}><span>{t.hero.characterRole}</span><strong>{t.hero.characterName} <ArrowUpRight size={17}/></strong><small>{t.hero.characterCatchphrase}</small></button><div className="hero-corner">{t.hero.fictionBadge}</div></section>
  <div className="news-ticker"><span className="ticker-title"><Zap size={15} fill="currentColor"/> {t.ticker.badge}</span><div><b>{t.ticker.item1Title}</b><span>{t.ticker.item1Desc}</span><i>✦</i><b>{t.ticker.item2Title}</b><span>{t.ticker.item2Desc}</span></div><span className="ticker-end">{t.ticker.end} <ArrowRight size={15}/></span></div>
  <section className="daily-section"><div className="section-heading"><div><span className="section-index">{t.daily.sectionIndex}</span><h2>{t.daily.title}</h2><span className="section-subtitle">{t.daily.subtitle}</span></div><button className="text-button" onClick={()=>navigate('stages')}>{t.daily.allStages} <ArrowRight size={15}/></button></div><div className="daily-grid"><div className="stage-grid">{stages.slice(0,3).map(s=>card(s))}</div><aside className="field-guide"><div className="guide-label"><BookOpen size={16}/><span>{t.daily.guideTitle}</span><span>{t.daily.guideTipBadge}</span></div><h3>{t.daily.guideHeading1}<br/><span>{t.daily.guideHeading2}</span><span className="guide-spark">✳</span></h3><div className="guide-diagram"><span className="diagram-person">◉<i/></span><span className="diagram-arc"/><b>90°</b><span className="diagram-baseline"/><small>{t.daily.guideSubtitle}</small></div><p>{t.daily.guideDescription.split('\n').map((line,idx)=><span key={idx}>{line}<br/></span>)}</p><button onClick={()=>void start(stages[0],true)}>{t.daily.practiceButton} <ArrowRight size={17}/></button></aside></div></section>
  <div className="bottom-strip"><div><ShieldCheck size={20}/><span><b>{t.bottomStrip.noFightTitle}</b><small>{t.bottomStrip.noFightDesc}</small></span></div><div><Headphones size={20}/><span><b>{t.bottomStrip.earphonesTitle}</b><small>{t.bottomStrip.earphonesDesc}</small></span><button onClick={()=>setDialog('calibration')}>{t.bottomStrip.earphonesButton} <ArrowUpRight size={12}/></button></div><div><AccessibilityIcon/><span><b>{t.bottomStrip.accessTitle}</b><small>{t.bottomStrip.accessDesc}</small></span><button onClick={()=>setDialog('options')}>{t.bottomStrip.accessButton} <ArrowUpRight size={12}/></button></div></div>
  </>:view==='stages'?<section className="browse-page"><div className="page-title"><div><span className="eyebrow">{t.browse.kicker}</span><h1>{t.browse.title}<span>{t.browse.subtitle}</span></h1><p>{t.browse.description}</p></div><div className="progress-stamp"><Trophy size={24}/><strong>{cleared.length}<small> / 30</small></strong><span>{t.browse.survivalCount}</span></div></div><div className="chapter-tabs">{t.browse.chapters.map((c,i)=><button className={chapter===i?'selected':''} key={c} onClick={()=>setChapter(i)}>{i>0&&<small>CH.{i} </small>}{c}</button>)}</div><p className="sample-note"><Sparkles size={15}/> {t.browse.sampleNotice}</p><div className="browse-grid">{stages.filter(s=>chapter===0||s.chapter===chapter).map(s=>card(s,true))}</div></section>:<section className="browse-page"><div className="page-title"><div><span className="eyebrow">{t.collection.kicker}</span><h1>{t.collection.title}<span>{t.collection.subtitle}</span></h1><p>{t.collection.description}</p></div><div className="progress-stamp"><BookOpen size={24}/><strong>{collection.length}<small> / 18</small></strong><span>{t.collection.collectedCount}</span></div></div><div className="collection-grid">{projectiles.map(([baseEmoji],i)=>{const [,pTitle,pDesc,pFlight]=getLocalizedProjectile(i,baseEmoji,lang);const isUnlocked=collection.includes(i);return <button key={i} className={`collection-card ${isUnlocked?'unlocked':'locked'}`} onClick={()=>setCollectInfo(i)}><span className="collection-number">NO. {String(i+1).padStart(2,'0')}</span><span className="projectile-emoji">{isUnlocked?baseEmoji:<LockKeyhole size={34}/>}</span><h3>{isUnlocked?pTitle:t.collection.lockedTitle}</h3><p>{isUnlocked?pDesc:t.collection.lockedDescription}</p><span className="flight-type">{isUnlocked?pFlight:t.collection.unseenFlight} <ChevronRight size={12}/></span></button>;})}</div></section>}</main>
  <footer><div className="footer-brand"><Megaphone size={18}/><b>PR PANIC</b><span>{lang==='ja'?'架空の会社。本物の冷や汗。':lang==='en'?'Fictional company. Genuine cold sweat.':'허구의 회사. 진짜 같은 식은땀.'}</span></div><div><button onClick={()=>setDialog('about')}>{t.nav.about}</button><span>·</span><button onClick={()=>setDialog('editor')}>{t.nav.editor}</button><span>·</span><button onClick={()=>setDialog('credits')}>{t.credits.title}</button><span className="footer-version">© 2026 PR PANIC · v1.0</span></div></footer>
  {dialog&&<Modal title={dialog==='options'?t.options.title:dialog==='calibration'?t.options.audio.latencyTitle:dialog==='howto'?t.howto.title:dialog==='about'?t.about.title:dialog==='editor'?t.editor.title:t.credits.title} kicker={dialog==='options'?t.options.kicker:dialog==='editor'?t.editor.kicker:t.howto.kicker} onClose={closeDialog} wide={dialog==='howto'||dialog==='editor'}>{dialog==='options'?<OptionsPanel onCalibrate={()=>setDialog('calibration')}/>:dialog==='calibration'?<Calibration/>:dialog==='howto'?<HowTo/>:dialog==='editor'?<Editor onPlay={s=>void start(s)}/>:dialog==='about'?<div className="about-content"><div className="about-portrait"><ManagerKim/><span>{t.about.badgeNote}</span></div><div className="about-tag">{t.about.tag}</div><h3>{t.about.headline}</h3><p>{t.about.bio.split('\n').map((line,idx)=><span key={idx}>{line}<br/></span>)}</p><div className="notice-box">{t.about.disclaimer}</div></div>:<div className="credits-content"><div className="credit-illustration"><Mic2 size={54}/><span>{t.credits.tagline1}<br/>{t.credits.tagline2}</span></div><p>{lang==='ja'?'すべての記者会見の裏には、\n何の落ち度もなく頭を下げる誰かがいます。':lang==='en'?'Behind every corporate press conference,\nsomeone is bowing with zero fault of their own.':'모든 기자회견의 뒤에는\n아무 잘못 없이 고개를 숙이는 누군가가 있습니다.'}</p><hr/><h3>{t.credits.gameTitle}</h3><p>{t.credits.info.split('\n').map((line,idx)=><span key={idx}>{line}<br/></span>)}</p><small>{t.credits.disclaimer}</small><button className="red-button" onClick={closeDialog}>{t.credits.confirmButton} <Check size={17}/></button></div>}</Modal>}
  {collectInfo!==null&&(()=>{const [emoji,title,desc,flight]=getLocalizedProjectile(collectInfo,projectiles[collectInfo][0],lang);const isUnlocked=collection.includes(collectInfo);return <Modal title={isUnlocked?title:t.collection.detailTitleLocked} kicker={`FIELD COLLECTION / NO. ${String(collectInfo+1).padStart(2,'0')}`} onClose={()=>setCollectInfo(null)}><div className="item-detail"><span>{isUnlocked?emoji:'?'}</span><p>{isUnlocked?desc:t.collection.detailDescLocked}</p><small>{isUnlocked?`${t.collection.flightTypeLabel}: ${flight} · ${t.collection.harmlessProp}`:t.collection.detailFlightLocked}</small><button className="outline-button" onClick={()=>{setCollectInfo(null);void start(stage);}}>{t.collection.backToConference} <ArrowRight size={16}/></button></div></Modal>;})()}
  </div>;
}

function AccessibilityIcon(){return <svg width="23" height="23" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7"><circle cx="12" cy="4" r="2"/><path d="M4 8L12 10 20 8M12 10V15M12 15L7 22M12 15L17 22"/></svg>}
